<?php

namespace App\Models;

use App\Helpers\Datatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class BaseModel extends Model
{
    use  SoftDeletes,Datatable;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->sort = self::query()->max('sort') + 1;
            if(auth('admin')->check())
                $model->admin_id=auth('admin')->id();
        });
    }

    function scopeSort($q, $type = 'desc')
    {
        $q->orderBy('sort', $type);
    }

    function scopeActive($q)
    {
        return $q->where('status', 1);
    }

    function admin()
    {
        return $this->belongsTo(Admin::class);
    }

}
