<?php

namespace App\Models;

use App\Helpers\Datatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;


class BaseModelAuth extends Authenticatable
{
    use  SoftDeletes;
    use HasFactory;
    use HasApiTokens;
    use Notifiable;
    use Datatable;

    protected $casts=['email_verified_at'=>'date'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->sort = self::query()->max('sort') + 1;
        });
    }

    function scopeSort($q, $type = 'desc')
    {
        $q->orderBy('sort', $type);
    }

    function scopeActive($q)
    {
        return $q->where('status', 1);
    }


    function getImage($size = '')
    {
        return $this->image ? ($this->image . ($size ? "/$size" : "")) : ("media/users/blank.png");
    }


}
