<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Admin\CreateUpdateAlbumRequest;
use App\Models\Album;
use Illuminate\Http\Request;

class AlbumController extends BaseController
{

    protected $modelClass = Album::class;
    protected $title = 'الألبومات';
    protected $route = 'albums';

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    function show(Album $album)
    {
        return redirect()->back()->with('msg', 'لا يوجد تفاصيل');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUpdateAlbumRequest $request)
    {
        //

        return $this->saveData($request->validated());
    }


    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Album $album
     * @return \Illuminate\Http\Response
     */
    public function update(CreateUpdateAlbumRequest $request, Album $album)
    {
        //
        return $this->saveData($request->validated(), $album);
    }

    public function saveData($data, $item = null)
    {
        $data['type'] = 'gallery';
        return parent::saveData($data, $item); // TODO: Change the autogenerated stub
    }

}
