<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Admin\CreateUpdateLetterRequest;
use App\Models\Letter;
use Illuminate\Http\Request;

class InvitationController extends BaseController
{

    protected $modelClass = Letter::class;
    protected $title = 'قوالب الدعوات';
    protected $route = 'invitations';
    protected $viewFolder = 'letters';

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */


    function index()
    {
        $query = $this->model->type('invitations');
        return $this->all($query);
    }

    function show(Letter $letter)
    {
        return redirect()->back()->with('msg', 'لا يوجد تفاصيل');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUpdateLetterRequest $request)
    {
        //

        return $this->saveData($request->validated());
    }


    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Letter $letter
     * @return \Illuminate\Http\Response
     */
    public function update(CreateUpdateLetterRequest $request, Letter $letter)
    {
        //
        return $this->saveData($request->validated(), $letter);
    }

    public function saveData($data, $item = null)
    {
        unset($data['images']);
        if (\request()->images) {
            $images = [];
            foreach (\request()->images as $image) {
                if (isset($image['file'])) {

                    $name = $image['file']->store("original");
                    $imgName = resize_image($name);
                    if ($imgName)
                        $images[] = $imgName;
                } else {
                    $images[] = $image['text'];

                }
            }
            $data['images'] = $images;
        }

        $data['type'] = 'invitations';
        return parent::saveData($data, $item); // TODO: Change the autogenerated stub
    }
}
